import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@/styles/globals.css";

import ProviderApollo from "@/providers/apolloProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Countries App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ProviderApollo>{children}</ProviderApollo>
      </body>
    </html>
  );
}
